services:
  conceptnavigator-quiz-service:
    build:
      context: ./QuizGenerationService
      dockerfile: Dockerfile
    container_name: conceptnavigator-quiz-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    networks:
      - conceptnavigator-network

networks: 
  conceptnavigator-network:
    driver: bridge
